### PR TITLE
Add tests for run()

### PR DESCRIPTION
**Pull request by hawkrives**
Success, input_data, timeout, and not found commands.

### CODE REVIEW

**Comment by hawkrives** [comment]
huh. I swear I ran the not-found test locally and it worked.

**Comment by rye** [comment]
This, too, looks good to me.

**Comment by rye** [comment]
In general, I think that adding spec files (as long as it doesn't touch actual code) is perfectly fine to just go ahead and merge after you get green CI—since it doesn't affect user-facing behavior, it should be fine.

**Comment by hawkrives** [comment]
Agreed.

**Pull request merged**
