### PR TITLE
Fix update check

### PR DESCRIPTION
**Pull request by maxnz**
- Added a `strip()` before lines are checked to see if they begin with `'<a'` - this was the main issue
- Increased timeout to 0.5s (from 0.01s) - 0.5 was the lowest reliable time I found. Maybe could be higher for slower connections.
- Reordered arguments in `main` (it said your current version was available and that you have the new version)
- Change `--update` to `--upgrade` in output
- Changed "update available" message to print to stderr

### CODE REVIEW

**Comment by hawkrives** [comment]
One thing: I'd like to start doing version bumps separately from PRs, so yeah :-)

**Comment by hawkrives** [comment]
Also, there was one blank line you removed - could you put that back, please?

**Comment by hawkrives** [comment]
I think the 0.01s timeout predates the 15-minutes check limit, so I had it to prevent slowdowns on every launch. I'm happy with 0.5s now.

**Comment by maxnz** [comment]
I think I put a print statement there while debugging and didn't realize it was an empty line at first

**Comment by maxnz** [comment]
Seriously PEP-8? "Blank line contains whitespace" causes a build failure?

**Comment by hawkrives** [comment]
Aight, can you revert the version bump and I'll merge?

**Comment by hawkrives** [comment]
@maxnz I'll tag a new version in about an hour

**Comment by maxnz** [comment]
Sounds good

**Pull request merged**
