### PR TITLE
Add spec update

### LINKED ISSUE #10: Automatically keep the local specs up-to-date
It would be nice if, instead of having to manually download and update the cs251-specs repository, the toolkit could automatically download and manage the specs for you.

So, instead of having to 

```console
$ git clone https://github.com/StoDevX/cs251-specs data
```

you could just

```console
$ cs251tk --record hw3
Updating specs… done.
Recording hw3 for rives, piersonv, magnusow
```

and have the toolkit itself keep them up to date.

---

I think they'd be stored in `$XDG_DATA_HOME`, with a fallback to `~/.local/share/cs251-specs` or `~/Library/Application Support/cs251-specs`. 

This issue should probably also include a new `--specs $dir` argument, to allow the user to provide a custom location to read spec files from.

### LINKED ISSUE #79: Toolkit not finding that pypi has an updated version
I've updated already to 2.3.0 and pypi now shows that 2.3.3 is available, but the toolkit isn't printing a "new version available" message.

### PR DESCRIPTION
**Pull request by maxnz**
Adds capability to check for spec updates with git fetch and a git log comparison. If an update is found, the user is asked if they want to pull the update from the remote repository.

If the data directory is not found, the user is asked if they want to download specs. If yes, it asks which class.
Fixes #79 and closes #10

### CODE REVIEW

**Comment by hawkrives** [comment]
My initial thought is that we should just automatically pull the updates, instead of asking. Thoughts?

**Comment by maxnz** [comment]
That probably would be better. If they don't want the updates, they can add the skip update check flag.

**Comment by hawkrives** [comment]
Agreed. I'll probably take a closer look at the rest of this PR later today, but it looks good so far!

**Comment by hawkrives** [comment]
For the future, @maxnz, I'd prefer it if we kept issues open until PRs were merged - GitHub will automatically close any issue that's attached to a PR. 

You can mark an issue for closure by saying "Closes #7" or whatever in the original post.

**Comment by maxnz** [comment]
Understandable. I think one was closed because I created a PR and linked them but then closed that PR because the changes were included here.

**Pull request merged**
