### PR TITLE
Improve first run experience for users

### PR DESCRIPTION
**Pull request by maxnz**
A HD TA contacted me this weekend asking why the toolkit wasn't setting up the student directories properly. The reason was because he forgot to include the `--course hd` flag. This prevents that from happening by changing the stogit url if the specs are being downloaded for the first time.

Also removed logging import (not used anymore).

### CODE REVIEW

**Comment by hawkrives** [comment]
I'm going to ignore those two codeclimate warnings.

**Comment by hawkrives** [comment]
… if I can figure out how to

**Comment by maxnz** [comment]
It looks like the codeclimate check it isn't required for merging.

**Comment by hawkrives** [comment]
I'll merge this for now. Long term, I'd like to move away from CodeClimate towards `pyflakes` or something, run in CI alongside the build process, where I can actually control the thing lol.

**Comment by rye** [comment]
You can run CodeClimate in CI… I think

**Comment by hawkrives** [comment]
Thanks! I still don't like the thing… but ok. I'm sure I could learn how to control it, but I'd rather just use something simpler.

**Comment by rye** [comment]
It's probably easier to run `pyflakes` in CI much as we do with `eslint` et al. in AAO than it is to control the CodeClimate behemoth.  It's not hard to add exceptions in CC, but it's easier if it actually triggers a build failure as you would expect.

**Comment by hawkrives** [comment]
yepyep

**Pull request merged**
