### PR TITLE
Add Referee support to the toolkit

### PR DESCRIPTION
**Pull request by hawkrives**
I made a referee binary-ish-thing in here!

It can read either from stdin, or as a singular argument.

```console
referee --stdin
referee [data]
```

where `[data]` is the JSON payload from [Gitlab's `push` event](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md#push-events).

1. It then analyzes the commit messages that Gitlab sends us for a very liberal interpretation of a homework/lab reference. (It matches the pattern `([a-z]+) ?(\d+)`, then checks the first group against `hw`, `homework`, `homeworks`, or `lab`.)

2. From that set of assignments, it then moves into a random temporary directory, so that we don't accidentally overwrite anything. (For all I know, this could be running multiple checks for the same student at once. If they somehow manage to submit two commits that quickly.)

3. Within that folder, we clone the repository from stogit, then check out the branch that the commits happened on.

4. Then we run the toolkit's `record` process on the assignments that we found earlier.

5. Finally, we remove the cloned folder.

6. Then, we turn the results into a plain-text, markdown-formatted email (we can make an html formatter if we'd like, later), connect to an smtp server on `localhost`, and send the email (from `cs251-tas@stolaf.edu`, I wasn't sure what to set it as.)

The email sending bit is probably going to take some tweaking on your end, @OmarShehata, but it might not – `sendmail` alone on those machines usually works.

So, all we should need to do now is:
- Install this on a machine
- Pull down the specs
- Put Joe's ssh key on the machine, so it can pull from stogit
- Hook this up to whatever service is going to pass us the JSON payload from the webhook
- Send a webhook event!

### CODE REVIEW

**Comment by hawkrives** [comment]
~250 of the additions are from https://github.com/StoDevX/cs251-toolkit/blob/382af5ba0b3a72f35b280e18c9e8b58f1187e0a3/test/assignment_parsing_test.py, where I took every commit from my students last semester that referenced an explicit homework/lab, and checked it against my algorithm.

**Comment by hawkrives** [comment]
To install this on a machine, I'd do:

> If we do the venv here, we don't need to worry about which python3 is getting used. `pyvenv` wasn't added until 3.4.

```console
mkdir cs251
cd cs251

pyvenv ./venv
source ./venv/bin/activate  # or activate.csh

git clone https://github.com/StoDevX/cs251-toolkit.git
cd cs251-toolkit
git checkout referee

python3 setup.py develop
cd ..  # back to cs251

deactivate

./venv/bin/referee --help
```

From here on out, you can refer to the `cs251/venv/bin/referee` binary from wherever; it'll use the right version of python.

So, you should then be able to just pass stdin to `cs251/venv/bin/referee --stdin` from whatever receives the data.

Have fun playing with this!

**Comment by hawkrives** [comment]
One addendum to my previous thing: currently, both `cs251tk` and `referee` expect to find the specs in `./data/specs`. We can add an argument for where to find them, if need be, or we can just be careful to invoke referee only in the cs251 folder.

**Comment by OmarShehata** [comment]
After some tests, we determined we need to:

- Run the [setup above](https://github.com/StoDevX/cs251-toolkit/pull/5#issuecomment-248897286) on a dedicated server (maybe pub.cs.stolaf.edu)
- Run a simple web server to receive POST event from Stogit and call referee with the given json payload
- Configure student repo's to call a webhook to server above on push events
- Configure remote smtp in `cs251/referee/send_email.py`

**Comment by hawkrives** [comment]
@OmarShehata, I think I'll merge this into `master` tonight (Tokyo) and push a new build (v2.1.0). Any issues that we need to fix we can do on `master`.

**Pull request merged**
