### PR TITLE
Bump version to v2.2.0

### PR DESCRIPTION
**Pull request by hawkrives**
After bumping, we just need to make a tag. We can do that via Github, by creating a "release".

## Changelog
- Finished initial implementation of the `referee` "server"

### CODE REVIEW

**Comment by hawkrives** [comment]
I made a draft release: https://github.com/StoDevX/cs251-toolkit/releases/edit/untagged-66ad5b1233ee1cd5d128

**Comment by hawkrives** [comment]
After we merge this PR, we can just push the "Publish Release" button to make a tag + deploy to PyPI.

**Comment by rye** [comment]
Okay, this makes sense.  Do you typically make a branch for every version bump?  Any particular reason for `#####` in the release body?

**Comment by hawkrives** [comment]
In the past, I haven't, because I've been the only person working on it.

I removed the level-6 heading and just stuck it in the "title" field, where it belongs.

I think it'd be a good idea to make a branch for each version in the future though, just so we can plan out release notes and make sure we didn't miss anything and such. Also so notifications are dispensed correctly.

**Comment by rye** [comment]
How about using `Version X.Y.Z: <Blah blah blah>` as opposed to `vX.Y.Z` for the release title?  And yeah, release notes are good.

**Comment by hawkrives** [comment]
Sure, that works for me. As long as we just make the tag be `vX.Y.Z`.

**Comment by rye** [comment]
Updated the release draft.

**Comment by rye** [comment]
So there's no code change that needs to be made?

**Comment by hawkrives** [comment]
Nope. Just the version bump in `setup.py`. IIRC, of course, but I don't think there's anything else to do.

**Comment by hawkrives** [comment]
Go ahead and make the release now, and let's watch the travis build.

**Comment by rye** [comment]
Released. 👍

**Comment by hawkrives** [comment]
The build: https://travis-ci.org/StoDevX/cs251-toolkit/builds/243056058

**Comment by hawkrives** [comment]
So the `^v` branch in `.travis.yml` is there because Travis regards tags as branches. So, without a `^v` whitelist, it'll never build the tagged commits, because their names don't match either of the other patterns.

**Comment by hawkrives** [comment]
… which is also why there are two builds for commit dfbf4e2. One because of master's HEAD being updated, and one because it's the first time Travis has seen the "branch" "v2.2.0".

**Comment by hawkrives** [comment]
`tags: true` does restrict the deploy section to only be released on tags – it's just the build ignition system that seems to conflate branches and tags.

**Comment by rye** [comment]
Ah, I see.  It probably has to do with ref parsing or something wonky.  In some of my past projects, I think I've successfully just tagged stuff and not needed anything in my configuration.  (See [builds on krye.io](https://travis-ci.org/rye/krye.io/branches), specifically the `v6.0.5` build which was specifically for a release.)

**Comment by rye** [comment]
(I.e. they might have fixed it sometime in the past, idk.)

**Comment by rye** [comment]
Looks like the builds all went well, [v2.2.0 is on PyPI](https://pypi.python.org/pypi/cs251tk/2.2.0), and the [appropriate tags](https://hub.docker.com/r/stodevx/cs251-toolkit/tags/) are pushed to Docker Hub!

**Comment by hawkrives** [comment]
wooT!

**Pull request merged**
